name: labhouse_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Style
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.4
  provider: ^6.0.5
  # Value equality
  equatable: ^2.0.5
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  dart_openai: ^4.0.0
  # Configuration
  global_configs: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Testing
  mocktail: ^1.0.0
  # Analysis
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
  - config/