name: labhouse_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Style
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.4
  provider: ^6.0.5
  rxdart: ^0.27.7
  # Value equality
  equatable: ^2.0.5
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  # Configuration
  global_configs: ^1.1.2
  # Media
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Testing
  mocktail: ^1.0.0
  # Analysis
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
  - config/

  fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat/Montserrat-Black.ttf
      - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
      - asset: fonts/Montserrat/Montserrat-Bold.ttf
      - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
      - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
      - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
      - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
      - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
      - asset: fonts/Montserrat/Montserrat-Italic.ttf
      - asset: fonts/Montserrat/Montserrat-Light.ttf
      - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
      - asset: fonts/Montserrat/Montserrat-Medium.ttf
      - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
      - asset: fonts/Montserrat/Montserrat-Regular.ttf
      - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
      - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
      - asset: fonts/Montserrat/Montserrat-Thin.ttf
      - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf